# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Mayukh Ghosh's Portfolio # This is what shows up in the tab of the browser



# Intro Section
name: Mayukh Ghosh
headline: Y2 Electrical Engineering Undergraduate at NUS
description: >- # dont remove this line. this will ignore all new lines until the next section
  Hello, I am currently a Year 2 international student studying Electrical Engineering at NUS. I have a keen interest in mathematics and its ubiquitous applications in engineering and technology. My primary areas of interest are control systems and signal analysis, although I also enjoy exploring other domains such as power systems and embedded systems. 


# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/pic_at_mt_fansipan.jpeg


# Link your resume
# You can place your resume in assets/resume/{resume.pdf or add external link such as pdf saved in google drive 
resume-url: ./assets/resume/resume.pdf


# Set up external links - this will show up as small icons next to your name.

external-links:    
  linkedin: https://www.linkedin.com/in/mayukh-ghosh-/
  github: https://github.com/AscendedSky
  #stackoverflow: test      # https://stackoverflow.com/users/{your url slug}
  #medium:            # https://medium.com/@{your url slug} 
  #x-twitter:   # https://x.com/{your url slug} 
  ##threads:            # https://threads.net/@{your url slug} 
  #instragram:       # https://instagram.com/{your url slug} 
  #youtube:           # https://youtube.com/@{your url slug} 
  #discord:            # https://discord.com/users/{your url slug} 
  #bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  tools:
    - Altium Designer
    - Fusion 360
    - LTSPICE
    - MATLAB (including Simulink)
    - GNU Octave
    - Qiskit
    - Git & GitHub
    - Docker
    - VS Code
    - STM32CubeIDE / PlatformIO
    - Make / CMake
    - Oscilloscope

  languages:
    - Python
    - C++
    - C
    - Java
    - Bash
    - Assembly 
    - Verilog 

  frameworks_libraries:
    ROS2:
    - MicroROS
    - Open-RMF
    - Navigation 2
    - MoveIt 2
    - Gazebo
    - Turtlebot 3
    python:
      - NumPy
      - Pandas
      - Matplotlib
      - SciPy
      - PyTorch
      - OpenCV
      - Scikit-Learn
      - Flask
      - FastAPI
  hardware:
    - PCB design & layout
    - Soldering
    - Microcontroller programming (ARM Cortex-M)


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
#formspree-key:   https://formspree.io/f/{8-digit key}



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors:
  text: "#e5e5e5"            # light gray text
  border: "#2a2a2a"          # dark gray borders
  link: "#5b8cff"            # soft blue links
  highlight: "#3d6dff"       # stronger blue for hover/active
  background: "#0d0d0d"      # near-black background
  light_background: "#1a1a1a" # slightly lighter sections

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
